/**
 * Poly Haven API (categories/textures, categories/models) 의 카테고리 어휘를
 * 타입 차원에 고정. 카탈로그 항목 메타 · public/{textures,models}/<cat>/ 폴더명 ·
 * 생성 URL 이 같은 리터럴을 공유해 typo/누락을 컴파일 타임에 차단한다.
 *
 * 'all' 과 'collection: *' 항목은 큐레이션 그룹이라 카테고리에서 제외.
 * API 가 카테고리 이름에 공백·하이픈을 그대로 쓰므로 union 리터럴도 동일 표기 유지.
 */
export type PolyHavenTextureCategory =
  | 'outdoor'
  | 'man made'
  | 'floor'
  | 'wall'
  | 'natural'
  | 'terrain'
  | 'plaster-concrete'
  | 'rock'
  | 'dirty'
  | 'brick'
  | 'concrete'
  | 'wood'
  | 'indoor'
  | 'sand'
  | 'clean'
  | 'fabric'
  | 'cobblestone'
  | 'road'
  | 'plaster'
  | 'aerial'
  | 'metal'
  | 'bark'
  | 'roofing'
  | 'asphalt'
  | 'raw wood'
  | 'tiles'
  | 'gravel'
  | 'sandstone'
  | 'snow'
  | 'cotton'
  | 'stretchy'
  | 'leather'
  | 'denim'
  | 'wool'
  | 'fleece'
  | 'knitted'
  | 'fur'
  | 'hessian'
  | 'industrial'
  | 'crepe'
  | 'jacquard'
  | 'food'
  | 'satin'
  | 'carpet'
  | 'corduroy'
  | 'suede'
  | 'woven'
  | 'velvet';

export type PolyHavenModelCategory =
  | 'props'
  | 'nature'
  | 'furniture'
  | 'industrial'
  | 'decorative'
  | 'plants'
  | 'containers'
  | 'tools'
  | 'rocks'
  | 'seating'
  | 'ground cover'
  | 'lighting'
  | 'structures'
  | 'table'
  | 'trees'
  | 'electronics'
  | 'food'
  | 'appliances'
  | 'shelves'
  | 'rigged'
  | 'buildings'
  | 'dishes'
  | 'vases'
  | 'flowers'
  | 'wall decoration'
  | 'office'
  | 'potted plants'
  | 'ships'
  | 'grass'
  | 'books'
  | 'bed'
  | 'instrument'
  | 'succulent'
  | 'weapons'
  | 'firearms'
  | 'creature';
