import type { FinishItem } from './types';

/**
 * 초기 마감재 카탈로그. 색·roughness는 현실 인테리어 자재 기준으로 대충 맞춤.
 * 단가는 시공 견적의 일반적인 범위(평당 시공비) 참고치 — 실제 운영 시 외부 데이터 소싱.
 *
 * 텍스처 맵은 Poly Haven CC0 슬러그 기준 (`public/textures/{slug}/` 에 사용자가 배치).
 * 맵 파일이 없으면 baseColor 단색으로 자연스럽게 폴백 (TextureLoader 실패는 콘솔 에러만).
 */
export const FINISH_CATALOG: readonly FinishItem[] = [
  {
    id: 'floor-oak',
    label: '오크 헤링본 마루',
    category: 'wood',
    applicableTo: ['floor'],
    baseColor: '#c9a574',
    roughness: 0.7,
    metalness: 0.0,
    baseColorMap: '/textures/herringbone_parquet/herringbone_parquet_diff_4k.jpg',
    normalMap: '/textures/herringbone_parquet/herringbone_parquet_nor_gl_4k.jpg',
    roughnessMap: '/textures/herringbone_parquet/herringbone_parquet_rough_4k.jpg',
    textureRepeatPerMeter: 0.5,
    pricePerSqmKRW: 180000,
  },
  {
    id: 'floor-walnut',
    label: '다크 우드 플랭크',
    category: 'wood',
    applicableTo: ['floor'],
    baseColor: '#6b4a32',
    roughness: 0.6,
    metalness: 0.0,
    baseColorMap: '/textures/dark_wooden_planks/dark_wooden_planks_diff_4k.jpg',
    normalMap: '/textures/dark_wooden_planks/dark_wooden_planks_nor_gl_4k.jpg',
    roughnessMap: '/textures/dark_wooden_planks/dark_wooden_planks_rough_4k.jpg',
    textureRepeatPerMeter: 0.5,
    pricePerSqmKRW: 230000,
  },
  {
    id: 'floor-marble-tile',
    label: '대리석 타일(바닥)',
    category: 'tile',
    applicableTo: ['floor', 'wall'],
    baseColor: '#e8e2d6',
    roughness: 0.25,
    metalness: 0.0,
    baseColorMap: '/textures/marble_01/marble_01_diff_4k.jpg',
    normalMap: '/textures/marble_01/marble_01_nor_gl_4k.jpg',
    roughnessMap: '/textures/marble_01/marble_01_rough_4k.jpg',
    textureRepeatPerMeter: 0.4,
    pricePerSqmKRW: 320000,
  },
  {
    id: 'floor-concrete-polished',
    label: '폴리싱 콘크리트',
    category: 'concrete',
    applicableTo: ['floor', 'wall'],
    baseColor: '#9b9893',
    roughness: 0.45,
    metalness: 0.0,
    baseColorMap: '/textures/concrete_floor/concrete_floor_diff_4k.jpg',
    normalMap: '/textures/concrete_floor/concrete_floor_nor_gl_4k.jpg',
    roughnessMap: '/textures/concrete_floor/concrete_floor_rough_4k.jpg',
    textureRepeatPerMeter: 0.35,
    pricePerSqmKRW: 140000,
  },
  {
    id: 'wall-paint-ivory',
    label: '아이보리 페인트',
    category: 'paint',
    applicableTo: ['wall', 'ceiling'],
    baseColor: '#f1ebe0',
    roughness: 0.95,
    metalness: 0.0,
    baseColorMap: '/textures/painted_plaster_wall/painted_plaster_wall_diff_4k.jpg',
    normalMap: '/textures/painted_plaster_wall/painted_plaster_wall_nor_gl_4k.jpg',
    roughnessMap: '/textures/painted_plaster_wall/painted_plaster_wall_rough_4k.jpg',
    textureRepeatPerMeter: 0.5,
    pricePerSqmKRW: 35000,
  },
  {
    id: 'wall-paint-charcoal',
    label: '차콜 페인트',
    category: 'paint',
    applicableTo: ['wall', 'ceiling'],
    baseColor: '#3a3a3e',
    roughness: 0.9,
    metalness: 0.0,
    baseColorMap: '/textures/grey_plaster_03/grey_plaster_03_diff_4k.jpg',
    normalMap: '/textures/grey_plaster_03/grey_plaster_03_nor_gl_4k.jpg',
    roughnessMap: '/textures/grey_plaster_03/grey_plaster_03_rough_4k.jpg',
    textureRepeatPerMeter: 0.5,
    pricePerSqmKRW: 38000,
  },
  {
    id: 'wall-wallpaper-linen',
    label: '리넨 회반죽',
    category: 'wallpaper',
    applicableTo: ['wall'],
    baseColor: '#d8cdb8',
    roughness: 0.88,
    metalness: 0.0,
    baseColorMap: '/textures/plastered_wall_02/plastered_wall_02_diff_4k.jpg',
    normalMap: '/textures/plastered_wall_02/plastered_wall_02_nor_gl_4k.jpg',
    roughnessMap: '/textures/plastered_wall_02/plastered_wall_02_rough_4k.jpg',
    textureRepeatPerMeter: 0.5,
    pricePerSqmKRW: 55000,
  },
  {
    id: 'wall-tile-subway',
    label: '서브웨이 타일',
    category: 'tile',
    applicableTo: ['wall'],
    baseColor: '#eeeeee',
    roughness: 0.3,
    metalness: 0.0,
    baseColorMap: '/textures/long_white_tiles/long_white_tiles_diff_4k.jpg',
    normalMap: '/textures/long_white_tiles/long_white_tiles_nor_gl_4k.jpg',
    roughnessMap: '/textures/long_white_tiles/long_white_tiles_rough_4k.jpg',
    // 서브웨이 타일은 자잘해야 디테일이 산다 — 미터당 반복 횟수 ↑
    textureRepeatPerMeter: 1.5,
    pricePerSqmKRW: 180000,
  },
  {
    id: 'ceiling-paint-white',
    label: '천장 화이트 페인트',
    category: 'paint',
    applicableTo: ['ceiling'],
    baseColor: '#fbfaf6',
    roughness: 0.95,
    metalness: 0.0,
    // 벽 페인트 슬러그를 재사용하되 반복 빈도를 줄여 톤만 살림
    baseColorMap: '/textures/painted_plaster_wall/painted_plaster_wall_diff_4k.jpg',
    normalMap: '/textures/painted_plaster_wall/painted_plaster_wall_nor_gl_4k.jpg',
    roughnessMap: '/textures/painted_plaster_wall/painted_plaster_wall_rough_4k.jpg',
    textureRepeatPerMeter: 0.3,
    pricePerSqmKRW: 32000,
  },
  // ---- 신규 6종 (마감재 셀렉터 다양성 + 견적 변동 폭 ↑) ----
  {
    id: 'floor-carpet',
    label: '카펫 바닥',
    category: 'wallpaper',
    applicableTo: ['floor'],
    baseColor: '#857060',
    roughness: 1.0,
    metalness: 0.0,
    baseColorMap: '/textures/dirty_carpet/dirty_carpet_diff_4k.jpg',
    normalMap: '/textures/dirty_carpet/dirty_carpet_nor_gl_4k.jpg',
    roughnessMap: '/textures/dirty_carpet/dirty_carpet_rough_4k.jpg',
    textureRepeatPerMeter: 0.6,
    pricePerSqmKRW: 90000,
  },
  {
    id: 'floor-laminate',
    label: '라미네이트 마루',
    category: 'wood',
    applicableTo: ['floor'],
    baseColor: '#b48a64',
    roughness: 0.55,
    metalness: 0.0,
    baseColorMap: '/textures/laminate_floor_02/laminate_floor_02_diff_4k.jpg',
    normalMap: '/textures/laminate_floor_02/laminate_floor_02_nor_gl_4k.jpg',
    roughnessMap: '/textures/laminate_floor_02/laminate_floor_02_rough_4k.jpg',
    textureRepeatPerMeter: 0.5,
    pricePerSqmKRW: 75000,
  },
  {
    id: 'wall-brick-red',
    label: '레드 브릭',
    category: 'tile',
    applicableTo: ['wall'],
    baseColor: '#9c5d4a',
    roughness: 0.85,
    metalness: 0.0,
    baseColorMap: '/textures/red_brick/red_brick_diff_4k.jpg',
    normalMap: '/textures/red_brick/red_brick_nor_gl_4k.jpg',
    roughnessMap: '/textures/red_brick/red_brick_rough_4k.jpg',
    textureRepeatPerMeter: 0.6,
    pricePerSqmKRW: 145000,
  },
  {
    id: 'wall-brick-painted',
    label: '페인트 벽돌',
    category: 'tile',
    applicableTo: ['wall'],
    baseColor: '#c97b6a',
    roughness: 0.9,
    metalness: 0.0,
    baseColorMap: '/textures/castle_brick_02_red/castle_brick_02_red_diff_4k.jpg',
    normalMap: '/textures/castle_brick_02_red/castle_brick_02_red_nor_gl_4k.jpg',
    roughnessMap: '/textures/castle_brick_02_red/castle_brick_02_red_rough_4k.jpg',
    textureRepeatPerMeter: 0.5,
    pricePerSqmKRW: 165000,
  },
  {
    id: 'wall-concrete-raw',
    label: '노출 콘크리트(벽)',
    category: 'concrete',
    applicableTo: ['wall', 'ceiling'],
    baseColor: '#a09c95',
    roughness: 0.85,
    metalness: 0.0,
    baseColorMap: '/textures/concrete_wall_007/concrete_wall_007_diff_4k.jpg',
    normalMap: '/textures/concrete_wall_007/concrete_wall_007_nor_gl_4k.jpg',
    roughnessMap: '/textures/concrete_wall_007/concrete_wall_007_rough_4k.jpg',
    textureRepeatPerMeter: 0.4,
    pricePerSqmKRW: 95000,
  },
  {
    id: 'ceiling-concrete-raw',
    label: '노출 콘크리트(천장)',
    category: 'concrete',
    applicableTo: ['ceiling'],
    baseColor: '#a09c95',
    roughness: 0.85,
    metalness: 0.0,
    // wall-concrete-raw 와 동일 슬러그 — repeat 만 다르게 천장 톤
    baseColorMap: '/textures/concrete_wall_007/concrete_wall_007_diff_4k.jpg',
    normalMap: '/textures/concrete_wall_007/concrete_wall_007_nor_gl_4k.jpg',
    roughnessMap: '/textures/concrete_wall_007/concrete_wall_007_rough_4k.jpg',
    textureRepeatPerMeter: 0.3,
    pricePerSqmKRW: 88000,
  },
] as const;

/** id로 카탈로그 항목 조회. 없으면 null. */
export function findFinish(id: string | null | undefined): FinishItem | null {
  if (!id) return null;
  return FINISH_CATALOG.find((f) => f.id === id) ?? null;
}
